-- 💰 ADMIN PROFIT WITHDRAWAL SYSTEM
-- This system tracks all profits and admin withdrawals for accurate business records

-- 1. Enhanced profit tracking table
CREATE TABLE IF NOT EXISTS admin_profits (
    id SERIAL PRIMARY KEY,
    transaction_type VARCHAR(50) NOT NULL, -- 'transfer', 'airtime', 'data', 'crypto'
    base_amount DECIMAL(15,2) NOT NULL,
    fee_amount DECIMAL(15,2) NOT NULL,
    profit_amount DECIMAL(15,2) NOT NULL,
    transaction_id VARCHAR(100),
    user_id TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    metadata JSONB DEFAULT '{}'::jsonb
);

-- 2. Admin withdrawal tracking table
CREATE TABLE IF NOT EXISTS admin_withdrawals (
    id SERIAL PRIMARY KEY,
    withdrawal_amount DECIMAL(15,2) NOT NULL,
    profit_balance_before DECIMAL(15,2) NOT NULL,
    profit_balance_after DECIMAL(15,2) NOT NULL,
    withdrawal_date TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    status VARCHAR(20) DEFAULT 'pending', -- 'pending', 'completed', 'cancelled'
    opay_completed BOOLEAN DEFAULT FALSE,
    opay_completion_date TIMESTAMP WITH TIME ZONE,
    notes TEXT,
    created_by TEXT DEFAULT 'admin',
    reminder_sent BOOLEAN DEFAULT FALSE
);

-- 3. Admin profit summary view
CREATE OR REPLACE VIEW admin_profit_summary AS
SELECT 
    COALESCE(SUM(profit_amount), 0) as total_profit_earned,
    COALESCE((SELECT SUM(withdrawal_amount) FROM admin_withdrawals WHERE status = 'completed'), 0) as total_withdrawn,
    COALESCE(SUM(profit_amount), 0) - COALESCE((SELECT SUM(withdrawal_amount) FROM admin_withdrawals WHERE status = 'completed'), 0) as available_profit,
    COUNT(*) as total_profit_transactions,
    MAX(created_at) as last_profit_date
FROM admin_profits;

-- 4. Indexes for performance
CREATE INDEX IF NOT EXISTS idx_admin_profits_created_at ON admin_profits(created_at);
CREATE INDEX IF NOT EXISTS idx_admin_profits_type ON admin_profits(transaction_type);
CREATE INDEX IF NOT EXISTS idx_admin_withdrawals_date ON admin_withdrawals(withdrawal_date);
CREATE INDEX IF NOT EXISTS idx_admin_withdrawals_status ON admin_withdrawals(status);

-- 5. Insert sample data to test
INSERT INTO admin_profits (transaction_type, base_amount, fee_amount, profit_amount, transaction_id, user_id, metadata)
VALUES 
    ('transfer', 5000.00, 25.00, 20.00, 'TRF001', 'user123', '{"recipient_bank": "GTBank"}'),
    ('airtime', 1000.00, 15.00, 10.00, 'AIR001', 'user456', '{"network": "MTN"}'),
    ('data', 2000.00, 20.00, 15.00, 'DATA001', 'user789', '{"network": "Airtel"}');

COMMENT ON TABLE admin_profits IS 'Tracks all profits generated by Sofi AI from various transaction types';
COMMENT ON TABLE admin_withdrawals IS 'Records admin profit withdrawals with Opay completion tracking';
COMMENT ON VIEW admin_profit_summary IS 'Provides real-time profit summary for admin dashboard';
