-- 🔧 MANUAL DATABASE FIXES FOR SOFI AI
-- Run these SQL commands in your Supabase SQL Editor

-- 1. Create user_daily_limits table
CREATE TABLE IF NOT EXISTS user_daily_limits (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    whatsapp_number TEXT NOT NULL,
    date DATE NOT NULL,
    total_transferred NUMERIC(15,2) DEFAULT 0.00,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW(),
    UNIQUE(whatsapp_number, date)
);

-- 2. Create index for user_daily_limits
CREATE INDEX IF NOT EXISTS idx_user_daily_limits_telegram_date 
ON user_daily_limits (whatsapp_number, date);

-- 3. Add balance column to virtual_accounts (if needed)
ALTER TABLE virtual_accounts 
ADD COLUMN IF NOT EXISTS balance NUMERIC(15,2) DEFAULT 0.00;

-- 4. Update existing virtual_accounts to have default balance
UPDATE virtual_accounts 
SET balance = 0.00 
WHERE balance IS NULL;

-- 5. Enable RLS on user_daily_limits
ALTER TABLE user_daily_limits ENABLE ROW LEVEL SECURITY;

-- 6. Create RLS policy for user_daily_limits
CREATE POLICY "Users can manage their own daily limits" ON user_daily_limits
FOR ALL USING (true)
WITH CHECK (true);
