services:
  - type: web
    name: sofi-ai-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn main:app --bind 0.0.0.0:$PORT --timeout 120 --workers 1"
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 10000
      - key: PYTHONPATH
        value: "."
    healthCheckPath: "/health"
    ports:
      - 10000
