services:
  - type: web
    name: sofi-ai-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn wsgi:application --bind 0.0.0.0:$PORT --workers 2 --timeout 120"
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PYTHONPATH
        value: "."
    healthCheckPath: "/health"
