#!/usr/bin/env python3
"""
Instructions for making a real transfer to test the receipt system
"""

print("🎯 HOW TO MAKE A REAL TRANSFER TO TEST RECEIPTS")
print("=" * 55)
print()
print("📱 STEP-BY-STEP INSTRUCTIONS:")
print("=" * 35)
print()
print("1️⃣  Start your Telegram bot:")
print("   📞 Go to Telegram and message your Sofi AI bot")
print("   💬 Send: /start")
print()
print("2️⃣  Check your balance:")
print("   💰 Send: /balance")
print("   📊 Make sure you have at least ₦150 for a ₦100 transfer")
print()
print("3️⃣  Start the transfer:")
print("   💸 Send: /transfer")
print("   🤖 Bot will ask for amount")
print("   💰 Reply: 100")
print()
print("4️⃣  Provide OPay details:")
print("   🏦 Bank: OPay Digital Services Limited")
print("   📱 Account: [Your OPay account number]")
print("   👤 Name: [Your full name as registered]")
print()
print("5️⃣  Confirm with PIN:")
print("   🔐 Enter your 4-digit PIN")
print("   ✅ Transfer will be processed")
print()
print("6️⃣  Receive beautiful receipt:")
print("   🧾 You'll get the new OPay-style receipt")
print("   📸 Both text and image versions")
print("   📊 Transaction logged in Supabase")
print()
print("🚨 IMPORTANT NOTES:")
print("=" * 20)
print("• This will transfer REAL money (₦100)")
print("• Make sure your OPay details are correct")
print("• You'll receive the money in your OPay account")
print("• The improved receipt will be sent to Telegram")
print("• All transaction data will be logged")
print()
print("🤖 Your Telegram Bot Token: 76995636...")
print("📞 Chat with your bot in Telegram to start!")
print()
print("💡 Alternative: Run the bot locally first:")
print("   python main.py")
print()
